### ISSUE TITLE
Has this Theme Disqus Support?

### ISSUE THREAD

**Issue by ghost** [bludit-themes/mediumish#1]
Hello Developers,

Your new bludit v3 theme looks very good and I just installed it, but unfortunately Disqus comments under Posts and Pages are no longer displayed.

Does the theme have Disqus support? I use Disqus from the plugin in Bludit CMS. 

Maybe this can still be realized! Otherwise nice design and good for me as a Bludit blogger.

Thanks in advance.

**Comment by dignajar** [comment]
Hi, I just release the version 1.1 of this theme with some bug fixes and one of them is what you mention.

**Comment by ghost** [comment]
Hi, thanks for your Work and my problem is now solved.
