### ISSUE TITLE
Can you test the Theme-Blog-Search

### ISSUE THREAD

**Issue by ghost** [bludit-themes/mediumish#2]
The blog search on this theme doesn't work. I entered simple terms and wanted to search the blog, but it says: "No pages found".

Can you please test the blog search again on your test project? Thanks in advance.

**Comment by dignajar** [comment]
The search function has not the best algortim, I'm testing in the demo and works fine.
Try to search some title of some page.

**Comment by ghost** [comment]
Searching for post/page titles doesn't seem to work in my blog. I don't know why yet. I tried to enter two search terms and search for them. Unfortunately also without success.

A while ago I migrated Bludit 2 to Bludit v3 and if it could be because of that. The first installation of the blog was based on Bludit v2.

**Comment by ghost** [comment]
Ok, Problem solved 👍 I had to activate and deactivate the search plugin. After that it worked. Thank you!

**Comment by dignajar** [comment]
Ok, I going to check the plugin, because maybe something is not triggering the generation of the cache database.
