### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by avilco** [bludit-themes/mediumish#4]
I try a new installation with bludit 3.4 and last version from github for this theme (with version 1.2 and last github) and when activate mediumish theme only top bar is showed.
See screenshots:
Mediumish theme
![bluditmediumish](https://user-images.githubusercontent.com/9807260/49338250-3e090e00-f61f-11e8-907a-60f520e81730.png)

Blog X Theme
![bluditblogx](https://user-images.githubusercontent.com/9807260/49338144-4b71c880-f61e-11e8-9f96-d64d2d1f1ae9.png)

**Comment by dignajar** [comment]
Hi,
can you udpate Bludit to the version 3.5 ?
The demo is running with Bludit v3.5 and Mediumish v1.2. https://demo.bludit.com/

Also, can you check the php_error.log ?

**Comment by avilco** [comment]
Hi, updated php from 5.3 to 5.6 and now works. It's possible that this theme requires php 5.6 ?

**Comment by dignajar** [comment]
I would like to see the php_error.log to check what happen, but if you already update the php version and works could be the problem. regards
