### ISSUE TITLE
Logo on mobile version

### ISSUE THREAD

**Issue by kendriii** [bludit-themes/mediumish#6]
Hi. On mobile view. How to move that logo to the corner right top ?
![IMG_20200524_143150](https://user-images.githubusercontent.com/65588744/82747462-84ca6500-9dcb-11ea-9375-5c06e49b5649.jpg)

**Comment by dignajar** [comment]
Hi, please ask in the forum (https://forum.bludit.org).
This section is for report issues and bugs.
Thanks
